### ISSUE TITLE
FR: Indicate already installed workflows

### ISSUE THREAD

**Issue by chrisgrieser** [alfredapp/alfred-gallery-workflow#2]
having a small emoji indicating that a workflow is already installed would be nice small QoL feature for this workflow :)

**Comment by vitorgalvao** [comment]
This was initially planned (with a few other related improvements) even before the issue was opened. However, there’d always be a tradeoff in performance because the cache is less predictable, which in turn would prevent other optimisations which have a bigger impact. This hasn’t had more requests, so closing and I’ll focus in the alternative direction.

Thank you for opening the request. I’ll keep this in the back of my mind and revisit later too.
